# Generated by Django 2.0.7 on 2018-07-22 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('avatar_url', models.URLField()),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('login', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(default=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('description', models.TextField(blank=True, null=True)),
                ('is_private', models.BooleanField()),
                ('primary_language', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('homepage_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('combined_slug', models.SlugField()),
                ('description', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='repositories',
            field=models.ManyToManyField(related_name='contributors', to='github.Repository'),
        ),
        migrations.AddField(
            model_name='member',
            name='teams',
            field=models.ManyToManyField(related_name='members', to='github.Team'),
        ),
    ]
