# Generated by Django 2.0.2 on 2018-03-03 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('profile_pic_url', models.URLField()),
                ('profile_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Repo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='No description')),
                ('language', models.CharField(max_length=255)),
                ('repo_url', models.URLField()),
                ('contributors', models.ManyToManyField(to='display.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='No description')),
                ('name', models.CharField(max_length=255)),
                ('team_url', models.URLField()),
                ('members', models.ManyToManyField(to='display.Member')),
                ('repos', models.ManyToManyField(to='display.Repo')),
            ],
        ),
    ]
