# Generated by Django 2.0.7 on 2018-07-30 04:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('approved', models.BooleanField(default=False)),
                ('members', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('project_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ProjectApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('FA', 'Fall'), ('SP', 'Spring'), ('SU', 'Summer'), ('WI', 'Winter')], default='SU', max_length=2)),
                ('year', models.IntegerField(choices=[(2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018)], default=2018)),
                ('created_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_creator', to='projects.Project')),
                ('first_choice', models.ForeignKey(limit_choices_to={'approved': True}, on_delete=django.db.models.deletion.CASCADE, related_name='first_choices', to='projects.Project')),
                ('second_choice', models.ForeignKey(blank=True, limit_choices_to={'approved': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_choices', to='projects.Project')),
                ('third_choice', models.ForeignKey(blank=True, limit_choices_to={'approved': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_choices', to='projects.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': '',
            },
        ),
        migrations.AlterUniqueTogether(
            name='projectapplication',
            unique_together={('user', 'semester', 'year')},
        ),
    ]
