# Generated by Django 2.0.7 on 2018-07-30 04:31

from django.db import migrations, models
import projects.managers


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ideal_capacity',
            field=models.FloatField(choices=[(0.05, 'Small'), (0.1, 'Medium'), (0.15, 'Large'), (0.2, 'X-Large')], default=0.1),
        ),
        migrations.AlterField(
            model_name='projectapplication',
            name='semester',
            field=models.CharField(choices=[('FA', 'Fall'), ('SP', 'Spring'), ('SU', 'Summer'), ('WI', 'Winter')], default=projects.managers.calculate_semester, max_length=2),
        ),
    ]
