# Generated by Django 2.0.4 on 2018-08-21 22:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 21, 22, 19, 47, 777891, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 21, 22, 19, 47, 777870, tzinfo=utc)),
        ),
    ]
