# Generated by Django 2.0.4 on 2018-08-21 23:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20180821_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 21, 23, 7, 3, 139267, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 21, 23, 7, 3, 139245, tzinfo=utc)),
        ),
    ]
