# Generated by Django 2.0.7 on 2018-07-24 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailinggroup',
            options={'permissions': (('send_mail', 'Can send mail to this MailingGroup'),)},
        ),
    ]
