# Generated by Django 2.0.4 on 2018-08-13 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailnotification',
            name='sending_user',
            field=models.ForeignKey(limit_choices_to={'staff': True}, on_delete=django.db.models.deletion.PROTECT, related_name='email_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='slackemailnotification',
            name='sending_user',
            field=models.ForeignKey(limit_choices_to={'staff': True}, on_delete=django.db.models.deletion.PROTECT, related_name='slack_email_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='slacknotification',
            name='sending_user',
            field=models.ForeignKey(limit_choices_to={'staff': True}, on_delete=django.db.models.deletion.PROTECT, related_name='slack_notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
