# Generated by Django 2.0.4 on 2018-08-14 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20180813_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailnotification',
            name='html_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='slackemailnotification',
            name='html_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emailnotification',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='slackemailnotification',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='slacknotification',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
