name: Node CI

on: [push]

jobs:
  check-formatting:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, compile, and check formatting
      run: |
        npm ci
        npm run check
      env:
        CI: true
